package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// HTTP code for type PostRequestlandingOK
const PostRequestlandingOKCode int = 200

/*PostRequestlandingOK OK

swagger:response postRequestlandingOK
*/
type PostRequestlandingOK struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewPostRequestlandingOK creates PostRequestlandingOK with default headers values
func NewPostRequestlandingOK() *PostRequestlandingOK {
	return &PostRequestlandingOK{}
}

// WithPayload adds the payload to the post requestlanding o k response
func (o *PostRequestlandingOK) WithPayload(payload string) *PostRequestlandingOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post requestlanding o k response
func (o *PostRequestlandingOK) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostRequestlandingOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}
