package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// HTTP code for type PostShipbayOK
const PostShipbayOKCode int = 200

/*PostShipbayOK OK

swagger:response postShipbayOK
*/
type PostShipbayOK struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewPostShipbayOK creates PostShipbayOK with default headers values
func NewPostShipbayOK() *PostShipbayOK {
	return &PostShipbayOK{}
}

// WithPayload adds the payload to the post shipbay o k response
func (o *PostShipbayOK) WithPayload(payload string) *PostShipbayOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post shipbay o k response
func (o *PostShipbayOK) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostShipbayOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}
