package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// PostShipbayHandlerFunc turns a function with the right signature into a post shipbay handler
type PostShipbayHandlerFunc func(PostShipbayParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostShipbayHandlerFunc) Handle(params PostShipbayParams) middleware.Responder {
	return fn(params)
}

// PostShipbayHandler interface for that can handle valid post shipbay params
type PostShipbayHandler interface {
	Handle(PostShipbayParams) middleware.Responder
}

// NewPostShipbay creates a new http.Handler for the post shipbay operation
func NewPostShipbay(ctx *middleware.Context, handler PostShipbayHandler) *PostShipbay {
	return &PostShipbay{Context: ctx, Handler: handler}
}

/*PostShipbay swagger:route POST /shipbay postShipbay

Land a ship in the ship bay

*/
type PostShipbay struct {
	Context *middleware.Context
	Handler PostShipbayHandler
}

func (o *PostShipbay) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, _ := o.Context.RouteInfo(r)
	var Params = NewPostShipbayParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
