package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// HTTP code for type PutExhaustportOK
const PutExhaustportOKCode int = 200

/*PutExhaustportOK OK

swagger:response putExhaustportOK
*/
type PutExhaustportOK struct {
}

// NewPutExhaustportOK creates PutExhaustportOK with default headers values
func NewPutExhaustportOK() *PutExhaustportOK {
	return &PutExhaustportOK{}
}

// WriteResponse to the client
func (o *PutExhaustportOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
}

// HTTP code for type PutExhaustportServiceUnavailable
const PutExhaustportServiceUnavailableCode int = 503

/*PutExhaustportServiceUnavailable Deathstar exploded

swagger:response putExhaustportServiceUnavailable
*/
type PutExhaustportServiceUnavailable struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewPutExhaustportServiceUnavailable creates PutExhaustportServiceUnavailable with default headers values
func NewPutExhaustportServiceUnavailable() *PutExhaustportServiceUnavailable {
	return &PutExhaustportServiceUnavailable{}
}

// WithPayload adds the payload to the put exhaustport service unavailable response
func (o *PutExhaustportServiceUnavailable) WithPayload(payload string) *PutExhaustportServiceUnavailable {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the put exhaustport service unavailable response
func (o *PutExhaustportServiceUnavailable) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PutExhaustportServiceUnavailable) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(503)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}
