package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import "encoding/json"

// SwaggerJSON embedded version of the swagger document used at generation time
var SwaggerJSON json.RawMessage

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "text/plain"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "API of a Star Wars Deathstar",
    "title": "Deathstar",
    "version": "v1"
  },
  "basePath": "/v1",
  "paths": {
    "/": {
      "get": {
        "summary": "Get in touch with the deathstar",
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "string"
            }
          }
        }
      }
    },
    "/exhaust-port": {
      "put": {
        "summary": "Put something into the thermal exhaust port of the deathstar",
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "string"
            }
          },
          "503": {
            "description": "Deathstar exploded",
            "schema": {
              "type": "string"
            }
          }
        }
      }
    },
    "/request-landing": {
      "post": {
        "summary": "Land a ship in the ship bay",
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "string"
            }
          }
        }
      }
    }
  }
}`))
}
